version: "3.9"
services:
  router1:
      privileged: true      
      image: mari1018/router1:1.0
      #image: routerale
      container_name: router1
      networks:
        #Ip del router en con LAN1
        macvlan1:
          #router1 : 10.0.0.99
          ipv4_address: 10.0.0.99

        #coneccion con LAN2
        macvlan2:
          #router2 : 10.0.1.98
          ipv4_address: 10.0.1.98
      cap_add:
        - NET_ADMIN
  router2:
      privileged: true      
      image: mari1018/router2:1.0
      #image: routerale
      container_name: router2
      networks:
        #Ip del router en con LAN1
        macvlan1:
          #router1 : 10.0.0.99
          ipv4_address: 10.0.0.98

        #coneccion con LAN2
        macvlan2:
          #router2 : 10.0.1.99
          ipv4_address: 10.0.1.99
      cap_add:
        - NET_ADMIN
  cliente:
        image: strm/nginx-balancer
        container_name: cliente-load-balancer
        ports:
          - "80:8080"
        environment:
          - "NODES=web1:80 web2:80"

  web1:
      image: mari1018/helloworld1:1.1
      # networks:
      #   macvlan1:
      #     #router1 : 10.0.0.99
      #     ipv4_address: 10.0.0.21

  web2:
      image: mari1018/helloworld2:1.1
      # networks:
      #   macvlan2:
      #     #router2 : 10.0.1.99
      #     ipv4_address: 10.0.1.21
  dns:
    privileged: true  
    build:
      context: ./DNS/
      dockerfile: dockerfile

    networks:
      macvlan1:
        ipv4_address: 10.0.0.3
    
    volumes:
      - ./Proyecto/DNS/bind/forward.google.com:/etc/bin/forward.google.com
      - ./Proyecto/DNS/bind/forward.lan01.io:/etc/bin/forward.lan01.io
      - ./Proyecto/DNS/bind/forward.lan02.io:/etc/bin/forward.lan02.io
      - ./Proyecto/DNS/bind/named.conf.local:/etc/bin/named.conf.local
      - ./Proyecto/DNS/bind/named.conf.options:/etc/bin/named.conf.options

  dhcp1:
    build: 
      context: ./DHCP1
      dockerfile: dockerfile

    restart: unless-stopped
    networks:
      macvlan1:
        ipv4_address: 10.0.0.4
    
    volumes:
      - ./Proyecto/dhcp1/data:/data networkboot/dhcpd

  dhcp2:
    build: 
      context: ./DHCP2
      dockerfile: dockerfile

    restart: unless-stopped
    networks:
      macvlan2:
        ipv4_address: 10.0.1.5

    ports:
      - 9666:9666

    volumes:
      - ./Proyecto/dhcp2/data:/data networkboot/dhcpd

volumes:
  config: {}

networks:
  macvlan1:
    driver: macvlan
    #driver_opts:
    #  parent: eth0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  
  macvlan2:
    driver: macvlan
    #driver_opts:
    #  parent: eth0
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
        
  brigde1:
    driver: bridge
    #driver_opts:
      #parent: eth0
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1
    